# Generated by Django 3.1 on 2022-04-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meatOrder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meatorder',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='小計'),
        ),
    ]
